# Generated by Django 3.2.16 on 2023-04-20 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0002_added_model_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={
                'default_related_name': 'comments',
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={
                'default_related_name': 'posts',
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
    ]
